begin;
create temporary table hamriq_test_ids as select gen_random_uuid() c1, gen_random_uuid() c2, gen_random_uuid() o1, gen_random_uuid() o2, gen_random_uuid() m1, gen_random_uuid() r1, gen_random_uuid() r2, gen_random_uuid() ct1, gen_random_uuid() ct2, gen_random_uuid() j1, gen_random_uuid() j2;
grant select on hamriq_test_ids to authenticated;
insert into public.companies(id,name,owner_email) select c1,'RLS test 1',o1::text||'@example.invalid' from hamriq_test_ids union all select c2,'RLS test 2',o2::text||'@example.invalid' from hamriq_test_ids;
insert into auth.users(id,email,email_confirmed_at,aud,role) select v.id,v.id::text||'@example.invalid',now(),'authenticated','authenticated' from hamriq_test_ids t cross join lateral (values(t.o1),(t.o2),(t.m1),(t.r1),(t.r2)) v(id);
insert into public.users(id,company_id,display_name,role) select v.id,c1,v.label,v.role::public.app_role from hamriq_test_ids t cross join lateral (values(t.m1,'Manager','manager'),(t.r1,'Rep 1','rep'),(t.r2,'Rep 2','rep')) v(id,label,role);
insert into public.contacts(id,company_id,assigned_to,name,created_by) select ct1,c1,r1,'Contact 1',o1 from hamriq_test_ids union all select ct2,c1,r2,'Contact 2',o1 from hamriq_test_ids;
insert into public.jobs(id,company_id,contact_id,assigned_to,title,address,created_by) select j1,c1,ct1,r1,'Job 1','Address',o1 from hamriq_test_ids union all select j2,c1,ct2,r2,'Job 2','Address',o1 from hamriq_test_ids;
update public.companies set access_mode='team' where id=(select c1 from hamriq_test_ids);
create temporary table runtime_test_records(key text primary key,id uuid,version integer,token text);
grant select,insert,update on runtime_test_records to authenticated;
grant select on runtime_test_records to anon;
select set_config('request.jwt.claim.sub',(select o1::text from hamriq_test_ids),true);
set local role authenticated;
do $$ declare r public.workspace_records; p jsonb; begin
 r:=public.save_workspace_record(null,null,'price','{"code":"TEST","name":"Test shingle","category":"Materials","unit":"square","price":125,"cost":90}',null);
 insert into runtime_test_records(key,id,version) values('price',r.id,r.version);
 r:=public.save_workspace_record(null,(select j1 from hamriq_test_ids),'cost','{"materials":100,"labor":50,"other":0,"revenue":300}',null);
 insert into runtime_test_records(key,id,version) values('cost',r.id,r.version);
 p:=public.create_workspace_portal((select j1 from hamriq_test_ids));
 insert into runtime_test_records(key,id,token) values('portal',(p->>'id')::uuid,p->>'token');
end $$;
reset role;
select set_config('request.jwt.claim.sub',(select r1::text from hamriq_test_ids),true);
set local role authenticated;
do $$ declare r public.workspace_records; begin
 if (select count(*) from public.workspace_records where kind='price')<>1 then raise exception 'Rep must read prices'; end if;
 if (select count(*) from public.workspace_records where kind='cost')<>0 then raise exception 'Rep finance leak'; end if;
 begin perform public.save_workspace_record(null,null,'price','{"code":"HACK","name":"x","category":"Materials","unit":"sq","price":1}',null);raise exception 'Rep price escalation';exception when insufficient_privilege then null;end;
 begin perform public.save_workspace_record(null,(select j2 from hamriq_test_ids),'note','{"body":"Other rep"}',null);raise exception 'Other rep job access';exception when insufficient_privilege then null;end;
 r:=public.save_workspace_record(null,(select j1 from hamriq_test_ids),'estimate','{"tier":"Good","scope":"Roof","lines":"TEST, 2","probability":50,"total":1}',null);
 if (r.payload->>'total')::numeric<>250 then raise exception 'Client forged estimate total'; end if;
 insert into runtime_test_records(key,id,version) values('estimate',r.id,r.version);
 begin perform public.transition_workspace_record(r.id,'approved',r.version);raise exception 'Self approval';exception when insufficient_privilege then null;end;
 begin insert into public.workspace_records(company_id,job_id,kind,payload,created_by) select c1,j1,'price','{}',r1 from hamriq_test_ids;raise exception 'Direct write bypass';exception when insufficient_privilege then null;end;
 begin perform public.create_workspace_portal((select j1 from hamriq_test_ids));raise exception 'Rep portal escalation';exception when insufficient_privilege then null;end;
end $$;
reset role;
select set_config('request.jwt.claim.sub',(select m1::text from hamriq_test_ids),true);
set local role authenticated;
do $$ declare r public.workspace_records; p jsonb;begin
 r:=public.transition_workspace_record((select id from runtime_test_records where key='estimate'),'approved',1);
 if r.status<>'approved' or r.approved_by<>auth.uid() then raise exception 'Approval attribution';end if;
 r:=public.save_workspace_record(r.id,r.job_id,r.kind,r.payload||'{"scope":"Updated roof"}'::jsonb,r.version);
 if r.status<>'pending_approval' or r.approved_by is not null then raise exception 'Edited approval survives';end if;
 begin perform public.save_workspace_record(r.id,r.job_id,r.kind,r.payload,1);raise exception 'Stale update accepted';exception when serialization_failure then null;end;
 r:=public.save_workspace_record(null,(select j1 from hamriq_test_ids),'claim','{"carrier":"Test","number":"123","milestone":"Filed","due":"2026-01-01","next":"Request update"}',null);
 perform public.run_workspace_automations();perform public.run_workspace_automations();
 if (select count(*) from public.workspace_records where payload->>'automation_ref' like 'deadline:'||r.id::text||'%')<>1 then raise exception 'Duplicate automation drafts';end if;
end $$;
reset role;
select set_config('request.jwt.claim.sub',(select o2::text from hamriq_test_ids),true);
set local role authenticated;
do $$ begin if exists(select 1 from public.workspace_records) then raise exception 'Cross-company runtime leak'; end if;end $$;
reset role;
select set_config('request.jwt.claim.sub','',true);
set local role anon;
do $$ declare p jsonb;begin
 p:=public.read_workspace_portal((select token from runtime_test_records where key='portal'));
 if p ? 'address' or p ? 'claim_number' or p ? 'notes' then raise exception 'Portal private data leak';end if;
 if not p ? 'stage' then raise exception 'Portal status missing';end if;
 begin perform public.save_workspace_record(null,null,'note','{"body":"anonymous"}',null);raise exception 'Anonymous write';exception when insufficient_privilege then null;end;
end $$;
reset role;
rollback;
select 'PASS: pricing authority, rep/finance/company isolation, approval versions, portal curation, idempotent automation; fixtures rolled back' result;
