import {inspectionChecks,readinessChecks} from './catalog.mjs';
export function localDay(date=new Date()){const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/Detroit',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date);const get=t=>parts.find(p=>p.type===t).value;return `${get('year')}-${get('month')}-${get('day')}`;}
export const money=value=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(value)||0);
export function missingInspection(p={}){return inspectionChecks.filter(k=>!p[k]);}
export function readiness(p={}){const missing=readinessChecks.filter(k=>!p[k]);return {ready:!missing.length,missing};}
export function parseLines(input){return String(input||'').split('\n').filter(s=>s.trim()).map(s=>{const i=s.lastIndexOf('|');if(i<1)throw Error('Use DESCRIPTION | AMOUNT for each line.');const name=s.slice(0,i).trim(),amount=Number(s.slice(i+1).trim());if(!Number.isFinite(amount)||amount<0)throw Error('Amounts must be nonnegative numbers.');return {name,amount};});}
export function estimateGaps(expected,carrier){const norm=s=>s.trim().toLowerCase().replace(/\s+/g,' ');const aggregate=lines=>{const m=new Map();for(const l of lines){const k=norm(l.name);m.set(k,(m.get(k)||0)+l.amount);}return m;};const a=aggregate(parseLines(expected)),b=aggregate(parseLines(carrier));return [...a].map(([name,amount])=>({name,expected:amount,carrier:b.get(name)||0,gap:Math.max(0,amount-(b.get(name)||0))})).filter(l=>l.gap>0);}
export function scheduleConflicts(candidate,records,exclude){if(candidate.end<candidate.start)throw Error('End date must be after start date.');return records.filter(r=>r.kind==='schedule'&&r.id!==exclude&&r.status!=='cancelled'&&r.payload.crew.trim().toLowerCase()===candidate.crew.trim().toLowerCase()&&r.payload.start<=candidate.end&&r.payload.end>=candidate.start);}
export function deliveryIssues(p,order){if(!order)return ['No approved material order to compare'];return ['product','color'].filter(k=>String(p[k]).trim().toLowerCase()!==String(order[k]).trim().toLowerCase()).map(k=>`${k} differs from order`).concat(Number(p.quantity)<Number(order.quantity)?['Quantity short']:[]);}
export function aging(p,now=new Date()){const balance=Math.max(0,Number(p.amount||0)-Number(p.paid||0));const days=Math.max(0,Math.floor((Date.parse(`${localDay(now)}T00:00:00Z`)-Date.parse(`${p.due}T00:00:00Z`))/86400000));return {balance,days,bucket:!days?'Current':days<=30?'1–30':days<=60?'31–60':days<=90?'61–90':'90+'};}
export function dueActions(records,now=new Date()){const day=localDay(now);return records.filter(r=>!['completed','cancelled','rejected'].includes(r.status)&&r.payload.due&&r.payload.due<=day);}
export function report(jobs,records){const options=records.filter(r=>r.kind==='estimate'&&r.status==='approved').sort((a,b)=>(b.updated_at||'').localeCompare(a.updated_at||''));const seen=new Set();const estimates=options.filter(r=>{if(seen.has(r.job_id))return false;seen.add(r.job_id);return true;});const forecast=estimates.reduce((n,r)=>n+Number(r.payload.total||0)*Math.min(100,Math.max(0,Number(r.payload.probability||0)))/100,0);const costs=records.filter(r=>r.kind==='cost');const revenue=costs.reduce((n,r)=>n+Number(r.payload.revenue||0),0),cost=costs.reduce((n,r)=>n+Number(r.payload.materials||0)+Number(r.payload.labor||0)+Number(r.payload.other||0),0);return {forecast,revenue,cost,profit:revenue-cost,conversion:jobs.length?jobs.filter(j=>['Signed','Complete'].includes(j.stage)).length/jobs.length*100:0};}
export function validatePayload(kind,p,definition){for(const f of definition.fields){const v=p[f.name];if(f.required&&(v===undefined||v===null||String(v).trim()===''))throw Error(`${f.label} is required.`);if(f.type==='number'&&v!==''&&v!==undefined&&(!Number.isFinite(Number(v))||Number(v)<0))throw Error(`${f.label} must be a nonnegative number.`);if(f.type==='select'&&!f.options.includes(v))throw Error(`Choose a valid ${f.label}.`);if(f.type==='date'&&v&&!/^\d{4}-\d{2}-\d{2}$/.test(v))throw Error(`Choose a valid ${f.label}.`);}if(kind==='review'&&p.rating&&(p.rating<1||p.rating>5))throw Error('Rating must be from 1 to 5.');if(kind==='commission'&&p.rate>100)throw Error('Commission rate cannot exceed 100%.');if(kind==='estimate'&&p.probability>100)throw Error('Probability cannot exceed 100%.');if(kind==='gap')estimateGaps(p.expected,p.carrier_lines);if(kind==='schedule'&&p.end<p.start)throw Error('End date must be after start date.');for(const key of ['url','logo','review_url'])if(p[key]&&!/^https:\/\//i.test(p[key]))throw Error('Links must start with https://.');return p;}
