import {byKey} from './catalog.mjs';
const uuid=()=>crypto.randomUUID();
export class DemoStore {
 constructor(customers){this.key='hamriq_workspace_v1';this.user={id:'demo-owner',display_name:'Demo Manager',role:'owner',company_id:'demo-company'};this.company={id:'demo-company',name:'hamrIQ Demo Roofing'};this.users=[this.user,{id:'demo-rep',display_name:'Mia Carter',role:'rep'}];this.demo=true;try{this.state=JSON.parse(localStorage.getItem(this.key));}catch{}if(!this.state){this.state={jobs:customers.map((c,i)=>({id:`demo-job-${i}`,contact_id:`demo-contact-${i}`,company_id:'demo-company',title:c.name,address:c.address,assigned_to:i%2?'demo-rep':'demo-owner',stage:i===7?'Complete':i>=5?'Signed':'Lead',created_at:new Date().toISOString()})),contacts:customers.map((c,i)=>({id:`demo-contact-${i}`,name:c.name,address:c.address,phone:c.phone,email:'',lead_source:c.source})),records:[],events:[],photos:[]};this.persist();}}
 persist(){localStorage.setItem(this.key,JSON.stringify(this.state));}
 async load(){return structuredClone(this.state);}
 async save(kind,job_id,payload,old){const def=byKey[kind];if(def.manager&&!['owner','manager'].includes(this.user.role))throw Error('Manager control required.');if(def.owner&&this.user.role!=='owner')throw Error('Owner control required.');if(kind==='estimate'){let total=0;payload.calculated_lines=payload.lines.split('\n').filter(s=>s.trim()).map(s=>{const [code,q,...extra]=s.split(',');const item=this.state.records.filter(r=>r.kind==='price'&&r.status!=='cancelled'&&r.payload.code.toLowerCase()===code.trim().toLowerCase()).at(-1);const quantity=Number(q);if(extra.length||!item||!Number.isFinite(quantity)||quantity<=0)throw Error(`Unknown price code or invalid quantity: ${code}`);const amount=Math.round(quantity*Number(item.payload.price)*100)/100;total+=amount;return {code:item.payload.code,name:item.payload.name,quantity,unit_price:Number(item.payload.price),amount};});if(!payload.calculated_lines.length)throw Error('Add price book lines.');payload.total=total;}
 const existing=old&&this.state.records.find(r=>r.id===old.id);if(existing&&existing.version!==old.version)throw Error('Record changed. Refresh first.');const r={id:old?.id||uuid(),company_id:this.company.id,job_id,kind,payload,status:def.approval?'pending_approval':'draft',created_by:old?.created_by||this.user.id,created_at:old?.created_at||new Date().toISOString(),updated_at:new Date().toISOString(),version:(old?.version||0)+1,approved_by:null};if(existing)this.state.records[this.state.records.indexOf(existing)]=r;else this.state.records.push(r);this.event(r,old?'updated; previous approval invalidated':'created');this.persist();return r;}
 event(r,action){this.state.events.push({id:uuid(),record_id:r.id,job_id:r.job_id,actor_id:this.user.id,action,occurred_at:new Date().toISOString()});}
 async transition(r,status){const actual=this.state.records.find(x=>x.id===r.id);if(actual.version!==r.version)throw Error('Record changed.');if(['approved','rejected'].includes(status)&&!['owner','manager'].includes(this.user.role))throw Error('Manager approval required.');if(status==='completed'&&byKey[r.kind].approval&&r.status!=='approved')throw Error('Approve before completion.');actual.status=status;actual.version++;actual.updated_at=new Date().toISOString();if(status==='approved'){actual.approved_by=this.user.id;actual.approved_at=actual.updated_at;}this.event(actual,status);this.persist();}
 async createLead(p){const contact={id:uuid(),name:p.name,address:p.address,phone:p.phone,email:p.email,lead_source:p.source};const j={id:uuid(),contact_id:contact.id,title:p.name,address:p.address,assigned_to:p.assigned||this.user.id,stage:'Lead',created_at:new Date().toISOString()};this.state.contacts.push(contact);this.state.jobs.push(j);this.persist();return j;}
 async stage(job,stage){this.state.jobs.find(j=>j.id===job.id).stage=stage;this.persist();}
 async upload(job,file,category,caption){if(file.size>8*1024*1024)throw Error('Demo images must be under 8 MB.');const url=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});const photo={id:uuid(),job_id:job.id,category,caption,url,uploaded_at:new Date().toISOString(),uploaded_by:this.user.id};this.state.photos.push(photo);try{this.persist();}catch(e){this.state.photos.pop();throw Error('Demo storage is full. Use smaller photos.');}return photo;}
 async photoUrl(p){return p.url;}
 async createPortal(){throw Error('Create homeowner links in the authenticated development app. Demo data is local to this browser.');}
}
export class LiveStore {
 constructor(db,context){this.db=db;this.user=context.user;this.company=context.company;this.demo=false;}
 async rows(table){const all=[];for(let page=0;page<100;page++){const {data,error}=await this.db.from(table).select('*').range(page*1000,page*1000+999);if(error)throw error;all.push(...data);if(data.length<1000)return all;}throw Error('Dataset exceeds workspace capacity. Narrow the workspace before loading.');}
 async load(){const [jobs,contacts,records,events,photos,users]=await Promise.all(['jobs','contacts','workspace_records','workspace_events','photos','users'].map(t=>this.rows(t)));this.users=users;return {jobs,contacts,records,events,photos};}
 async rpc(name,p){const {data,error}=await this.db.rpc(name,p);if(error)throw error;return data;}
 async save(kind,job_id,payload,old){return this.rpc('save_workspace_record',{p_id:old?.id||null,p_job:job_id,p_kind:kind,p_payload:payload,p_version:old?.version||null});}
 async transition(r,status){return this.rpc('transition_workspace_record',{p_id:r.id,p_status:status,p_version:r.version});}
 async createLead(p){return this.rpc('create_workspace_lead',{p_name:p.name,p_address:p.address,p_phone:p.phone,p_email:p.email,p_source:p.source,p_assigned:p.assigned||null});}
 async stage(job,stage){const {error}=await this.db.from('jobs').update({stage}).eq('id',job.id);if(error)throw error;}
 async upload(job,file,category,caption){if(file.size>25*1024*1024)throw Error('Files must be under 25 MB.');if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('Choose JPEG, PNG or WebP.');const ext={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[file.type];const path=`${this.company.id}/${job.id}/${uuid()}.${ext}`;let result=await this.db.storage.from('job-files').upload(path,file,{contentType:file.type,upsert:false});if(result.error)throw result.error;const {data,error}=await this.db.from('photos').insert({company_id:this.company.id,job_id:job.id,storage_path:path,category,caption,uploaded_by:this.user.id}).select().single();if(error){await this.db.storage.from('job-files').remove([path]);throw error;}return data;}
 async photoUrl(p){const {data,error}=await this.db.storage.from('job-files').createSignedUrl(p.storage_path,300);if(error)throw error;return data.signedUrl;}
 async createPortal(job){return this.rpc('create_workspace_portal',{p_job:job.id});}
 async portalLinks(){return this.rows('workspace_portal_links');}
 async revokePortal(id){return this.rpc('revoke_workspace_portal',{p_id:id});}
 async analyze(job,photos,question){const {data:{session}}=await this.db.auth.getSession();if(!session)throw Error('Sign in again.');const res=await fetch('/api/assistant',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({job_id:job.id,photo_ids:photos.map(p=>p.id),question})});const body=await res.json();if(!res.ok)throw Error(body.error||'AI request failed');return body.result;}
}
